import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/app/lib/auth"

export const metadata: Metadata = {
  title: "Turbo AI notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
